apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: mnist-classifier
  namespace: mlteam
spec:
  predictor:
    tolerations:
      - key: "nvidia.com/gpu"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
    triton:
      storageUri: "pvc://mnist-pipeline-storage/models"
      # nvcr.io/nvidia/tritonserver:25.12-py3
      runtimeVersion: "25.12-py3"
      resources:
        requests:
          cpu: "1"
          memory: "4Gi"
          nvidia.com/gpu: "1"
        limits:
          cpu: "2"
          memory: "8Gi"
          nvidia.com/gpu: "1"
