apiVersion: v1
kind: ConfigMap
metadata:
  name: mnist-test-script
  namespace: ml-team-a
data:
  test.py: |
    import numpy as np
    import requests
    import json
    from PIL import Image, ImageDraw, ImageFont

    # KServe 엔드포인트
    INFERENCE_URL = "http://mnist-classifier-predictor.ml-team-a.svc.cluster.local/v2/models/mnist/infer"

    def create_digit_image(digit):
        """테스트용 숫자 이미지 생성"""
        img = Image.new('L', (28, 28), color=0)
        draw = ImageDraw.Draw(img)
        
        try:
            font = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf", 20)
        except:
            font = ImageFont.load_default()
        
        bbox = draw.textbbox((0, 0), str(digit), font=font)
        w, h = bbox[2] - bbox[0], bbox[3] - bbox[1]
        draw.text(((28-w)/2, (28-h)/2 - 2), str(digit), fill=255, font=font)
        
        return np.array(img, dtype=np.float32)

    def preprocess(image_array):
        """이미지 전처리"""
        image = (image_array / 255.0 - 0.1307) / 0.3081
        return image.reshape(1, 28, 28).astype(np.float32)

    def predict(image):
        """KServe V2 프로토콜로 추론 요청"""
        payload = {
            "inputs": [
                {
                    "name": "input",
                    "shape": [1, 1, 28, 28],
                    "datatype": "FP32",
                    "data": image.flatten().tolist()
                }
            ]
        }
        
        headers = {"Content-Type": "application/json"}
        response = requests.post(INFERENCE_URL, headers=headers, json=payload)
        
        if response.status_code != 200:
            print(f"Error: {response.status_code}")
            print(response.text)
            return None, None, None
        
        result = response.json()
        logits = np.array(result["outputs"][0]["data"])
        
        # Softmax
        exp_logits = np.exp(logits - np.max(logits))
        probs = exp_logits / exp_logits.sum()
        
        predicted = np.argmax(probs)
        confidence = probs[predicted] * 100
        
        return predicted, confidence, probs

    def main():
        print("=" * 50)
        print("MNIST Digit Recognition Test (KServe)")
        print("=" * 50)
        
        # 서버 상태 확인
        health_url = "http://mnist-classifier-predictor.ml-team-a.svc.cluster.local/v2/health/ready"
        try:
            response = requests.get(health_url, timeout=5)
            if response.status_code == 200:
                print("✅ KServe server is ready\n")
            else:
                print(f"❌ Server not ready: {response.status_code}")
                return
        except Exception as e:
            print(f"❌ Cannot connect to server: {e}")
            return
        
        # 0-9 모든 숫자 테스트
        print("Testing digits 0-9:")
        print("-" * 40)
        
        correct = 0
        for digit in range(10):
            img = create_digit_image(digit)
            processed = preprocess(img)
            
            predicted, confidence, probs = predict(processed)
            
            if predicted is None:
                print(f"❌ Input: {digit} → Error")
                continue
            
            status = "✅" if predicted == digit else "❌"
            print(f"{status} Input: {digit} → Predicted: {predicted} ({confidence:.1f}%)")
            
            if predicted == digit:
                correct += 1
        
        print("-" * 40)
        print(f"Accuracy: {correct}/10 ({correct*10}%)")
        
        # 상세 테스트
        print("\n" + "=" * 50)
        print("Detailed test for digit '7':")
        print("=" * 50)
        
        img = create_digit_image(7)
        processed = preprocess(img)
        predicted, confidence, probs = predict(processed)
        
        if probs is not None:
            print(f"Predicted: {predicted} (confidence: {confidence:.2f}%)\n")
            print("All probabilities:")
            for i, p in enumerate(probs):
                bar = "█" * int(p * 30)
                print(f"  {i}: {bar} {p*100:.2f}%")
        
        print("\n✅ Test completed!")

    if __name__ == "__main__":
        main()
---
apiVersion: v1
kind: Pod
metadata:
  name: mnist-test
  namespace: ml-team-a
spec:
  containers:
    - name: test
      image: python:3.10-slim
      command:
        - /bin/bash
        - -c
        - |
          pip install requests numpy pillow -q
          python /workspace/test.py
      volumeMounts:
        - name: scripts
          mountPath: /workspace
  volumes:
    - name: scripts
      configMap:
        name: mnist-test-script
  restartPolicy: Never
