apiVersion: trainer.kubeflow.org/v1alpha1
kind: TrainingRuntime
metadata:
  name: multi-node-torch-distributed
  namespace: jhchoi
  labels:
    trainer.kubeflow.org/framework: torch
spec:
  mlPolicy:
    numNodes: 2
    torch:
      numProcPerNode: 1  # 노드당 GPU Count
  template:
    spec:
      replicatedJobs:
        - name: node
          template:
            metadata:
              labels:
                trainer.kubeflow.org/trainjob-ancestor-step: trainer
            spec:
              template:
                metadata:
                  labels:
                    # kai-scheduler가 동일한 PodGroup으로 묶도록 설정
                    kai.scheduler/podgroup-name: "trainjob-multi-node-ddp-gang"
                  annotations:
                    # minMember 설정 - 2개 Pod이 모두 스케줄링되어야 함
                    kai.scheduler/podgroup-min-available: "2"
                spec:
                  schedulerName: kai-scheduler
                  containers:
                    - name: node
                      image: nvcr.io/nvidia/pytorch:25.01-py3
