apiVersion: trainer.kubeflow.org/v1alpha1
kind: TrainingRuntime
metadata:
  name: multi-node-torch-distributed
  namespace: jhchoi
  labels:
    trainer.kubeflow.org/framework: torch
spec:
  mlPolicy:
    numNodes: 2
    torch:
      numProcPerNode: 1
  template:
    spec:
      replicatedJobs:
        - name: node
          template:
            metadata:
              labels:
                trainer.kubeflow.org/trainjob-ancestor-step: trainer
            spec:
              template:
                metadata:
                  annotations:
                    # kai-scheduler가 기존 PodGroup을 사용하도록 지정
                    kai.scheduler/podgroup-name: "trainjob-multi-node-ddp-gang"
                spec:
                  schedulerName: kai-scheduler
                  containers:
                    - name: node
                      image: nvcr.io/nvidia/pytorch:25.01-py3
