# ============================================
# Stable Diffusion - Distributed Fine-tuning
# LoRA / DreamBooth with Accelerate (2 Nodes)
# ============================================
---
apiVersion: trainer.kubeflow.org/v1alpha1
kind: TrainingRuntime
metadata:
  name: stable-diffusion-runtime
  namespace: mlteam
spec:
  mlPolicy:
    numNodes: 2
    torch:
      numProcPerNode: auto
  template:
    spec:
      replicatedJobs:
        - name: trainer
          replicas: 1
          template:
            spec:
              parallelism: 2
              completions: 2
              template:
                spec:
                  schedulerName: kai-scheduler
                  initContainers:
                    - name: git-clone
                      image: alpine/git
                      command:
                        - sh
                        - -c
                        - |
                          git clone --depth=1 https://github.com/ds2qdu/train-model.git /workspace/repo
                          cp /workspace/repo/trainjob/mjob06-stable-diffusion/train.py /workspace/train.py
                          echo "Git clone completed"
                          ls -la /workspace/
                      volumeMounts:
                        - name: workspace
                          mountPath: /workspace
                  containers:
                    - name: trainer
                      image: nvcr.io/nvidia/pytorch:25.12-py3
                      command:
                        - bash
                        - -c
                        - |
                          # Install dependencies
                          echo "=== Installing Stable Diffusion dependencies ==="
                          pip install --root-user-action=ignore \
                            diffusers[torch] \
                            transformers \
                            accelerate \
                            safetensors \
                            peft \
                            datasets \
                            Pillow \
                            ftfy

                          # Environment setup
                          export HF_HOME=/mnt/storage/huggingface
                          export TRANSFORMERS_CACHE=/mnt/storage/huggingface

                          # Distributed training environment
                          export WORLD_SIZE=2
                          export RANK=${JOB_COMPLETION_INDEX:-0}
                          export MASTER_PORT=29500
                          export LOCAL_RANK=0

                          # Get master address
                          MY_IP=$(hostname -i | awk '{print $1}')

                          if [ "$RANK" == "0" ]; then
                              export MASTER_ADDR=$MY_IP
                          else
                              echo "Waiting for master pod..."
                              for i in $(seq 1 60); do
                                  MASTER_ADDR=$(getent ahostsv4 stable-diffusion-training.mlteam.svc.cluster.local 2>/dev/null | awk '{print $1}' | grep -v "^${MY_IP}$" | head -1)
                                  if [ -n "$MASTER_ADDR" ]; then
                                      echo "Found master: $MASTER_ADDR"
                                      break
                                  fi
                                  echo "Waiting... ($i/60)"
                                  sleep 1
                              done
                              export MASTER_ADDR
                          fi

                          echo "=== Distributed Training Config ==="
                          echo "WORLD_SIZE: $WORLD_SIZE"
                          echo "RANK: $RANK"
                          echo "MASTER_ADDR: $MASTER_ADDR"
                          echo "MASTER_PORT: $MASTER_PORT"
                          echo "MY_IP: $MY_IP"

                          echo "=== GPU Information ==="
                          nvidia-smi

                          # Worker waits for master port
                          if [ "$RANK" != "0" ]; then
                              echo "Waiting for master port..."
                              for i in $(seq 1 120); do
                                  if timeout 1 bash -c "</dev/tcp/$MASTER_ADDR/$MASTER_PORT" 2>/dev/null; then
                                      echo "Master is ready!"
                                      break
                                  fi
                                  sleep 1
                              done
                          fi

                          # Run distributed training with accelerate
                          echo "=== Starting Distributed Stable Diffusion Fine-tuning ==="
                          cd /mnt/storage

                          accelerate launch \
                            --num_processes=$WORLD_SIZE \
                            --num_machines=$WORLD_SIZE \
                            --machine_rank=$RANK \
                            --main_process_ip=$MASTER_ADDR \
                            --main_process_port=$MASTER_PORT \
                            --mixed_precision=fp16 \
                            --dynamo_backend=no \
                            /workspace/train.py \
                            --model_name "runwayml/stable-diffusion-v1-5" \
                            --train_data_dir /mnt/storage/data/train \
                            --output_dir /mnt/storage/models \
                            --train_method lora \
                            --epochs 100 \
                            --batch_size 1 \
                            --learning_rate 1e-4 \
                            --resolution 512

                          echo "=== Training Complete ==="
                      env:
                        - name: HF_HOME
                          value: "/mnt/storage/huggingface"
                        - name: TRANSFORMERS_CACHE
                          value: "/mnt/storage/huggingface"
                        - name: NCCL_DEBUG
                          value: "INFO"
                        - name: NCCL_IB_DISABLE
                          value: "1"
                        - name: NCCL_SOCKET_IFNAME
                          value: "eth0"
                        - name: NCCL_NET
                          value: "Socket"
                        - name: TOKENIZERS_PARALLELISM
                          value: "false"
                      resources:
                        requests:
                          cpu: "4"
                          memory: "24Gi"
                          nvidia.com/gpu: "1"
                        limits:
                          cpu: "8"
                          memory: "32Gi"
                          nvidia.com/gpu: "1"
                      volumeMounts:
                        - name: shm
                          mountPath: /dev/shm
                        - name: workspace
                          mountPath: /workspace
                        - name: storage
                          mountPath: /mnt/storage
                  volumes:
                    - name: shm
                      emptyDir:
                        medium: Memory
                        sizeLimit: 16Gi
                    - name: workspace
                      emptyDir: {}
                    - name: storage
                      persistentVolumeClaim:
                        claimName: stable-diffusion-storage
                  restartPolicy: OnFailure
---
apiVersion: trainer.kubeflow.org/v1alpha1
kind: TrainJob
metadata:
  name: stable-diffusion-training
  namespace: mlteam
  annotations:
    kai.scheduler/queue: "mlteam-queue"
spec:
  runtimeRef:
    name: stable-diffusion-runtime
    kind: TrainingRuntime
    apiGroup: trainer.kubeflow.org
  trainer:
    image: nvcr.io/nvidia/pytorch:25.12-py3
    numNodes: 2
    numProcPerNode: 1
    resourcesPerNode:
      requests:
        cpu: "4"
        memory: "24Gi"
        nvidia.com/gpu: "1"
      limits:
        cpu: "8"
        memory: "32Gi"
        nvidia.com/gpu: "1"
    env:
      - name: NCCL_DEBUG
        value: "INFO"
      - name: NCCL_IB_DISABLE
        value: "1"
      - name: NCCL_SOCKET_IFNAME
        value: "eth0"
      - name: NCCL_NET
        value: "Socket"
  podTemplateOverrides:
    - targetJobs:
        - name: trainer
      spec:
        tolerations:
          - key: "nvidia.com/gpu"
            operator: "Equal"
            value: "true"
            effect: "NoSchedule"
