---
apiVersion: v1
kind: Service
metadata:
  name: stock-training
  namespace: mlteam
spec:
  clusterIP: None
  selector:
    jobset.sigs.k8s.io/jobset-name: stock-training
  ports:
    - name: torchrun
      port: 29500
      targetPort: 29500
