apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stock-pipeline-storage
  namespace: mlteam
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-client
