---
apiVersion: trainer.kubeflow.org/v1alpha1
kind: TrainingRuntime
metadata:
  name: stock-runtime
  namespace: mlteam
spec:
  mlPolicy:
    numNodes: 2
    torch:
      numProcPerNode: auto
  template:
    spec:
      replicatedJobs:
        - name: trainer
          replicas: 1
          template:
            spec:
              parallelism: 2
              completions: 2
              template:
                spec:
                  schedulerName: kai-scheduler
                  initContainers:
                    - name: git-clone
                      image: alpine/git
                      command:
                        - sh
                        - -c
                        - |
                          git clone --depth=1 https://github.com/ds2qdu/train-model.git /workspace/repo
                          cp /workspace/repo/trainjob/mjob04-stock/train.py /workspace/train.py
                          echo "Git clone completed"
                          ls -la /workspace/
                      volumeMounts:
                        - name: workspace
                          mountPath: /workspace
                  containers:
                    - name: trainer
                      image: nvcr.io/nvidia/pytorch:25.12-py3
                      command:
                        - bash
                        - -c
                        - |
                          # Install dependencies
                          echo "=== Installing dependencies ==="
                          pip install --root-user-action=ignore yfinance scikit-learn transformers chromadb
                          echo "=== Dependencies installed successfully ==="

                          # Environment setup
                          export WORLD_SIZE=2
                          export RANK=${JOB_COMPLETION_INDEX:-0}
                          export MASTER_PORT=29500
                          export LOCAL_RANK=0

                          # MASTER_ADDR: Rank 0 uses its own IP, workers find rank 0's IP
                          MY_IP=$(hostname -i | awk '{print $1}')

                          if [ "$RANK" == "0" ]; then
                              export MASTER_ADDR=$MY_IP
                          else
                              echo "Waiting for master pod..."
                              echo "My IP: $MY_IP"
                              for i in $(seq 1 60); do
                                  MASTER_ADDR=$(getent ahostsv4 stock-training.mlteam.svc.cluster.local 2>/dev/null | awk '{print $1}' | grep -v "^${MY_IP}$" | head -1)
                                  if [ -n "$MASTER_ADDR" ]; then
                                      echo "Found master: $MASTER_ADDR"
                                      break
                                  fi
                                  echo "Waiting... ($i/60)"
                                  sleep 1
                              done
                              export MASTER_ADDR
                          fi

                          echo "=== Environment ==="
                          echo "WORLD_SIZE=$WORLD_SIZE"
                          echo "RANK=$RANK"
                          echo "MASTER_ADDR=$MASTER_ADDR"
                          echo "MASTER_PORT=$MASTER_PORT"
                          echo "MY_IP=$MY_IP"
                          echo ""

                          # Worker waits for master port
                          if [ "$RANK" != "0" ]; then
                              echo "Waiting for master port..."
                              for i in $(seq 1 120); do
                                  if timeout 1 bash -c "</dev/tcp/$MASTER_ADDR/$MASTER_PORT" 2>/dev/null; then
                                      echo "Master is ready!"
                                      break
                                  fi
                                  sleep 1
                              done
                          fi

                          torchrun \
                            --nnodes=$WORLD_SIZE \
                            --nproc_per_node=1 \
                            --node_rank=$RANK \
                            --master_addr=$MASTER_ADDR \
                            --master_port=$MASTER_PORT \
                            /workspace/train.py \
                            --epochs=100 \
                            --batch-size=32 \
                            --lr=0.0001 \
                            --seq-length=30 \
                            --pred-length=5 \
                            --d-model=256 \
                            --nhead=8 \
                            --num-layers=4 \
                            --data-dir=/mnt/storage/data \
                            --checkpoint-dir=/mnt/storage/checkpoints \
                            --export-dir=/mnt/storage/models \
                            --chromadb-dir=/mnt/storage/chromadb \
                            --resume
                      env:
                        - name: NCCL_DEBUG
                          value: "INFO"
                        - name: NCCL_IB_DISABLE
                          value: "1"
                        - name: NCCL_SOCKET_IFNAME
                          value: "eth0"
                        - name: NCCL_NET
                          value: "Socket"
                        - name: FINNHUB_API_KEY
                          value: "demo"  # Replace with your API key or use Secret
                        - name: HF_HOME
                          value: "/mnt/storage/huggingface"
                        - name: PIP_USE_FEATURE
                          value: "build-constraint"
                      resources:
                        requests:
                          cpu: "4"
                          memory: "16Gi"
                          nvidia.com/gpu: "1"
                        limits:
                          cpu: "8"
                          memory: "32Gi"
                          nvidia.com/gpu: "1"
                      volumeMounts:
                        - name: shm
                          mountPath: /dev/shm
                        - name: workspace
                          mountPath: /workspace
                        - name: storage
                          mountPath: /mnt/storage
                  volumes:
                    - name: shm
                      emptyDir:
                        medium: Memory
                        sizeLimit: 8Gi
                    - name: workspace
                      emptyDir: {}
                    - name: storage
                      persistentVolumeClaim:
                        claimName: stock-pipeline-storage
                  restartPolicy: OnFailure
---
apiVersion: trainer.kubeflow.org/v1alpha1
kind: TrainJob
metadata:
  name: stock-training
  namespace: mlteam
  annotations:
    kai.scheduler/queue: "mlteam-queue"
spec:
  runtimeRef:
    name: stock-runtime
    kind: TrainingRuntime
    apiGroup: trainer.kubeflow.org
  trainer:
    image: nvcr.io/nvidia/pytorch:25.12-py3
    numNodes: 2
    numProcPerNode: 1
    resourcesPerNode:
      requests:
        cpu: "4"
        memory: "16Gi"
        nvidia.com/gpu: "1"
      limits:
        cpu: "8"
        memory: "32Gi"
        nvidia.com/gpu: "1"
    env:
      - name: NCCL_DEBUG
        value: "INFO"
      - name: NCCL_IB_DISABLE
        value: "1"
      - name: NCCL_SOCKET_IFNAME
        value: "eth0"
      - name: NCCL_NET
        value: "Socket"
  podTemplateOverrides:
    - targetJobs:
        - name: trainer
      spec:
        tolerations:
          - key: "nvidia.com/gpu"
            operator: "Equal"
            value: "true"
            effect: "NoSchedule"
